application: beato-2014
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: beato.application

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
